/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InsuranceReminderService } from "../insuranceReminder.service";
import { InsuranceReminderCreateInput } from "./InsuranceReminderCreateInput";
import { InsuranceReminder } from "./InsuranceReminder";
import { InsuranceReminderFindManyArgs } from "./InsuranceReminderFindManyArgs";
import { InsuranceReminderWhereUniqueInput } from "./InsuranceReminderWhereUniqueInput";
import { InsuranceReminderUpdateInput } from "./InsuranceReminderUpdateInput";
import { BikerFindManyArgs } from "../../biker/base/BikerFindManyArgs";
import { Biker } from "../../biker/base/Biker";
import { BikerWhereUniqueInput } from "../../biker/base/BikerWhereUniqueInput";

export class InsuranceReminderControllerBase {
  constructor(protected readonly service: InsuranceReminderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: InsuranceReminder })
  async createInsuranceReminder(
    @common.Body() data: InsuranceReminderCreateInput
  ): Promise<InsuranceReminder> {
    return await this.service.createInsuranceReminder({
      data: {
        ...data,

        biker: data.biker
          ? {
              connect: data.biker,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        reminderDate: true,

        biker: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [InsuranceReminder] })
  @ApiNestedQuery(InsuranceReminderFindManyArgs)
  async insuranceReminders(
    @common.Req() request: Request
  ): Promise<InsuranceReminder[]> {
    const args = plainToClass(InsuranceReminderFindManyArgs, request.query);
    return this.service.insuranceReminders({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        reminderDate: true,

        biker: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: InsuranceReminder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async insuranceReminder(
    @common.Param() params: InsuranceReminderWhereUniqueInput
  ): Promise<InsuranceReminder | null> {
    const result = await this.service.insuranceReminder({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        reminderDate: true,

        biker: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: InsuranceReminder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInsuranceReminder(
    @common.Param() params: InsuranceReminderWhereUniqueInput,
    @common.Body() data: InsuranceReminderUpdateInput
  ): Promise<InsuranceReminder | null> {
    try {
      return await this.service.updateInsuranceReminder({
        where: params,
        data: {
          ...data,

          biker: data.biker
            ? {
                connect: data.biker,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          reminderDate: true,

          biker: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: InsuranceReminder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInsuranceReminder(
    @common.Param() params: InsuranceReminderWhereUniqueInput
  ): Promise<InsuranceReminder | null> {
    try {
      return await this.service.deleteInsuranceReminder({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          reminderDate: true,

          biker: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bikers")
  @ApiNestedQuery(BikerFindManyArgs)
  async findBikers(
    @common.Req() request: Request,
    @common.Param() params: InsuranceReminderWhereUniqueInput
  ): Promise<Biker[]> {
    const query = plainToClass(BikerFindManyArgs, request.query);
    const results = await this.service.findBikers(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        email: true,
        username: true,

        voiceChatRoom: {
          select: {
            id: true,
          },
        },

        insuranceReminder: {
          select: {
            id: true,
          },
        },

        location: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bikers")
  async connectBikers(
    @common.Param() params: InsuranceReminderWhereUniqueInput,
    @common.Body() body: BikerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bikers: {
        connect: body,
      },
    };
    await this.service.updateInsuranceReminder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bikers")
  async updateBikers(
    @common.Param() params: InsuranceReminderWhereUniqueInput,
    @common.Body() body: BikerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bikers: {
        set: body,
      },
    };
    await this.service.updateInsuranceReminder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bikers")
  async disconnectBikers(
    @common.Param() params: InsuranceReminderWhereUniqueInput,
    @common.Body() body: BikerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bikers: {
        disconnect: body,
      },
    };
    await this.service.updateInsuranceReminder({
      where: params,
      data,
      select: { id: true },
    });
  }
}
