/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  VoiceChatRoom as PrismaVoiceChatRoom,
  Biker as PrismaBiker,
} from "@prisma/client";

export class VoiceChatRoomServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.VoiceChatRoomCountArgs, "select">
  ): Promise<number> {
    return this.prisma.voiceChatRoom.count(args);
  }

  async voiceChatRooms(
    args: Prisma.VoiceChatRoomFindManyArgs
  ): Promise<PrismaVoiceChatRoom[]> {
    return this.prisma.voiceChatRoom.findMany(args);
  }
  async voiceChatRoom(
    args: Prisma.VoiceChatRoomFindUniqueArgs
  ): Promise<PrismaVoiceChatRoom | null> {
    return this.prisma.voiceChatRoom.findUnique(args);
  }
  async createVoiceChatRoom(
    args: Prisma.VoiceChatRoomCreateArgs
  ): Promise<PrismaVoiceChatRoom> {
    return this.prisma.voiceChatRoom.create(args);
  }
  async updateVoiceChatRoom(
    args: Prisma.VoiceChatRoomUpdateArgs
  ): Promise<PrismaVoiceChatRoom> {
    return this.prisma.voiceChatRoom.update(args);
  }
  async deleteVoiceChatRoom(
    args: Prisma.VoiceChatRoomDeleteArgs
  ): Promise<PrismaVoiceChatRoom> {
    return this.prisma.voiceChatRoom.delete(args);
  }

  async findBikers(
    parentId: string,
    args: Prisma.BikerFindManyArgs
  ): Promise<PrismaBiker[]> {
    return this.prisma.voiceChatRoom
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .bikers(args);
  }

  async getBiker(parentId: string): Promise<PrismaBiker | null> {
    return this.prisma.voiceChatRoom
      .findUnique({
        where: { id: parentId },
      })
      .biker();
  }
}
