/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { VoiceChatRoomWhereUniqueInput } from "../../voiceChatRoom/base/VoiceChatRoomWhereUniqueInput";
import { Type } from "class-transformer";
import { LocationUpdateManyWithoutBikersInput } from "./LocationUpdateManyWithoutBikersInput";
import { InsuranceReminderWhereUniqueInput } from "../../insuranceReminder/base/InsuranceReminderWhereUniqueInput";
import { InsuranceReminderUpdateManyWithoutBikersInput } from "./InsuranceReminderUpdateManyWithoutBikersInput";
import { VoiceChatRoomUpdateManyWithoutBikersInput } from "./VoiceChatRoomUpdateManyWithoutBikersInput";
import { LocationWhereUniqueInput } from "../../location/base/LocationWhereUniqueInput";

@InputType()
class BikerUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;

  @ApiProperty({
    required: false,
    type: () => VoiceChatRoomWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VoiceChatRoomWhereUniqueInput)
  @IsOptional()
  @Field(() => VoiceChatRoomWhereUniqueInput, {
    nullable: true,
  })
  voiceChatRoom?: VoiceChatRoomWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => LocationUpdateManyWithoutBikersInput,
  })
  @ValidateNested()
  @Type(() => LocationUpdateManyWithoutBikersInput)
  @IsOptional()
  @Field(() => LocationUpdateManyWithoutBikersInput, {
    nullable: true,
  })
  locations?: LocationUpdateManyWithoutBikersInput;

  @ApiProperty({
    required: false,
    type: () => InsuranceReminderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => InsuranceReminderWhereUniqueInput)
  @IsOptional()
  @Field(() => InsuranceReminderWhereUniqueInput, {
    nullable: true,
  })
  insuranceReminder?: InsuranceReminderWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => InsuranceReminderUpdateManyWithoutBikersInput,
  })
  @ValidateNested()
  @Type(() => InsuranceReminderUpdateManyWithoutBikersInput)
  @IsOptional()
  @Field(() => InsuranceReminderUpdateManyWithoutBikersInput, {
    nullable: true,
  })
  insuranceReminders?: InsuranceReminderUpdateManyWithoutBikersInput;

  @ApiProperty({
    required: false,
    type: () => VoiceChatRoomUpdateManyWithoutBikersInput,
  })
  @ValidateNested()
  @Type(() => VoiceChatRoomUpdateManyWithoutBikersInput)
  @IsOptional()
  @Field(() => VoiceChatRoomUpdateManyWithoutBikersInput, {
    nullable: true,
  })
  voiceChatRooms?: VoiceChatRoomUpdateManyWithoutBikersInput;

  @ApiProperty({
    required: false,
    type: () => LocationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => LocationWhereUniqueInput)
  @IsOptional()
  @Field(() => LocationWhereUniqueInput, {
    nullable: true,
  })
  location?: LocationWhereUniqueInput | null;
}

export { BikerUpdateInput as BikerUpdateInput };
