/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  IsOptional,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { VoiceChatRoom } from "../../voiceChatRoom/base/VoiceChatRoom";
import { Location } from "../../location/base/Location";
import { InsuranceReminder } from "../../insuranceReminder/base/InsuranceReminder";

@ObjectType()
class Biker {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username!: string | null;

  @ApiProperty({
    required: false,
    type: () => VoiceChatRoom,
  })
  @ValidateNested()
  @Type(() => VoiceChatRoom)
  @IsOptional()
  voiceChatRoom?: VoiceChatRoom | null;

  @ApiProperty({
    required: false,
    type: () => [Location],
  })
  @ValidateNested()
  @Type(() => Location)
  @IsOptional()
  locations?: Array<Location>;

  @ApiProperty({
    required: false,
    type: () => InsuranceReminder,
  })
  @ValidateNested()
  @Type(() => InsuranceReminder)
  @IsOptional()
  insuranceReminder?: InsuranceReminder | null;

  @ApiProperty({
    required: false,
    type: () => [InsuranceReminder],
  })
  @ValidateNested()
  @Type(() => InsuranceReminder)
  @IsOptional()
  insuranceReminders?: Array<InsuranceReminder>;

  @ApiProperty({
    required: false,
    type: () => [VoiceChatRoom],
  })
  @ValidateNested()
  @Type(() => VoiceChatRoom)
  @IsOptional()
  voiceChatRooms?: Array<VoiceChatRoom>;

  @ApiProperty({
    required: false,
    type: () => Location,
  })
  @ValidateNested()
  @Type(() => Location)
  @IsOptional()
  location?: Location | null;
}

export { Biker as Biker };
